"""Adding views to posts

Revision ID: 738f5c746d91
Revises: fa023da5c80b
Create Date: 2024-08-11 12:03:10.360378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738f5c746d91'
down_revision: Union[str, None] = 'fa023da5c80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
